### PR TITLE
added more features

### PR DESCRIPTION
**Pull request by colameo**
screen shot 2016-10-05 at 8 35 34

### CODE REVIEW

**Comment by cbornet** [comment]
It looks really nice !
I don't see how I can wire this to vscode through LSP though :disappointed: ...

**Comment by jbadeau** [comment]
https://github.com/ashinw/vscode-plantuml-ext

**Comment by cbornet** [comment]
Yes, I saw that. The problem is to get the output from JdlDiagramTextProvider. I don't see how to do that.

**Comment by colameo** [comment]
I've started yesterday evening implementing a component which can be reused everywhere.
I'll commit it this evening...

**Pull request merged**
