### PR TITLE
Add vscode support

### PR DESCRIPTION
**Pull request by cbornet**
Notes:
* The VSCode plugin is a npm project so it's kind of awkward to mix it with the multi-modules maven project. We could do a separate project but for this we would need to have a packaged "jdl.ide" executable (script + jar libs) downloadable somewhere.
* For the appassembler-maven-plugin to correctly detect the dependencies, I had to give them explicitly in the pom.xml.
* To build and test the extension, one must:
  * copy io.github.jhipster.jdl.ide/target/appassembler/* to io.github.jhipster.jdl.vscode/xtext-server-jdl/ (for gradle there is a `installServer` task, nothing for maven right now)
  * run `npm install` in io.github.jhipster.jdl.vscode folder
  * open io.github.jhipster.jdl.vscode in vscode
  * enter F5
* To publish the extension, see https://code.visualstudio.com/docs/tools/vscecli

### CODE REVIEW

**Comment by cbornet** [comment]
Great !
When you tag the next release, we can publish an official extension.
cc @jdubois

**Comment by cbornet** [comment]
@colameo when do you think we can tag a new version ?

**Comment by colameo** [comment]
...i'm quite busy at the moment, but soon  :-) end of this or next week

**Comment by cbornet** [comment]
Great :+1:  !

**Pull request merged**
